version: '2'

networks:
  test:

services:
#organization 1 and organization 2 are two organization used in our project and 1 orderer organization for CA
  ca_org1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054" #Port where CA will be running 
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' #Username and pass for admin users
    volumes: #Volume is mounted to store confidential information of the CA1 and CA2
      - ./fabric-ca/org1:/etc/hyperledger/fabric-ca-server
    container_name: ca.org1.example.com
    hostname: ca.org1.example.com
    networks: #ntwrok name is test
      - test

  ca_org2:
    image: hyperledger/fabric-ca
    environment: #environment variables
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/org2:/etc/hyperledger/fabric-ca-server
    container_name: ca.org2.example.com
    hostname: ca.org2.example.com
    networks:
      - test

  ca_orderer:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - test
